<?php
namespace App\Controllers;
class BorrowRequestsController extends BaseController {
 public function index(){try{$this->borrowingService()->refreshOverdue();}catch(\Throwable){}return view('borrow_requests/index',['title'=>$this->role()==='borrower'?'My Requests':'Borrow Requests','requests'=>$this->repository()->borrowRequests($this->role(),$this->userId(),($s=(string)$this->request->getGet('status'))?:null)]);}
 public function create(){return view('borrow_requests/create',['title'=>'New Borrowing Request','equipment'=>$this->repository()->equipmentOptions()]);}
 public function store(){if(!$this->validate(['purpose'=>'required|max_length[2000]','requested_date'=>'required|valid_date[Y-m-d]','expected_return_date'=>'required|valid_date[Y-m-d]']))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());$ids=$this->request->getPost('equipment_id');$qtys=$this->request->getPost('quantity');$items=[];if(is_array($ids)&&is_array($qtys)){foreach($ids as $i=>$id)$items[]=['equipment_id'=>(int)$id,'quantity'=>(int)($qtys[$i]??0)];}try{$id=$this->borrowingService()->createRequest($this->userId(),['purpose'=>$this->postString('purpose'),'requested_date'=>$this->postString('requested_date'),'expected_return_date'=>$this->postString('expected_return_date'),'notes'=>$this->postString('notes')],$items);return redirect()->to('/borrow-requests/'.$id)->with('success','Borrowing request submitted.');}catch(\Throwable $e){return redirect()->back()->withInput()->with('error',$this->safeErrorMessage($e,'Request could not be submitted.'));}}
 public function show(int $id){$request=$this->repository()->findBorrowRequest($id);if(!$request)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();if($this->role()==='borrower'&&(int)$request['borrower_id']!==$this->userId())return redirect()->to('/borrow-requests')->with('error','You do not have access to that request.');return view('borrow_requests/show',['title'=>$request['request_number'],'request'=>$request,'items'=>$this->repository()->borrowRequestItems($id)]);}
 public function cancel(int $id){try{$this->borrowingService()->cancel($id,$this->userId());return redirect()->to('/borrow-requests/'.$id)->with('success','Request cancelled.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'Request could not be cancelled.'));}}
 public function approve(int $id){try{$this->borrowingService()->approve($id,$this->userId());return redirect()->back()->with('success','Request approved.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'Request could not be approved.'));}}
 public function reject(int $id){try{$this->borrowingService()->reject($id,$this->userId(),$this->postString('rejection_reason'));return redirect()->back()->with('success','Request rejected.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'Request could not be rejected.'));}}
 public function release(int $id){$conditions=$this->request->getPost('condition_on_release');try{$this->borrowingService()->release($id,$this->userId(),is_array($conditions)?$conditions:[]);return redirect()->back()->with('success','Equipment release recorded.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'Equipment could not be released.'));}}
 public function recordReturn(int $id){$conditions=$this->request->getPost('condition_on_return');$notes=$this->request->getPost('damage_notes');try{$this->borrowingService()->returnAll($id,$this->userId(),is_array($conditions)?$conditions:[],is_array($notes)?$notes:[]);return redirect()->back()->with('success','Equipment return recorded.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'Return could not be recorded.'));}}
}
