<?php
namespace App\Controllers;
use App\Application\Services\AuditService;use App\Models\EquipmentLocationModel;
class EquipmentLocationsController extends BaseController {
 public function index(){return view('equipment_locations/index',['title'=>'Equipment Locations','rows'=>$this->repository()->locations()]);}
 public function store(){return $this->save(null);} public function update(int $id){return $this->save($id);}
 public function status(int $id){$status=$this->postString('status');if(!in_array($status,['active','inactive'],true))return redirect()->back()->with('error','Invalid status.');$m=new EquipmentLocationModel();$row=$m->find($id);if(!$row)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();try{$m->update($id,['status'=>$status]);(new AuditService())->log($this->userId(),'location_status','equipment_location',$id,ucfirst($status).' equipment location '.$row['name']);return redirect()->back()->with('success','Location status updated.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'Location status could not be updated.'));}}
 private function save(?int $id){$context=$id===null?[]:['edit_location_id'=>$id];if(!$this->validate('equipmentLocation')){$r=redirect()->back()->withInput()->with('errors',$this->validator->getErrors());foreach($context as $k=>$v)$r=$r->with($k,$v);return $r;}$m=new EquipmentLocationModel();$name=$this->postString('name');$dup=$m->where('name',$name);if($id)$dup->where('id !=',$id);if($dup->first()){$r=redirect()->back()->withInput()->with('errors',['name'=>'Location name already exists.']);foreach($context as $k=>$v)$r=$r->with($k,$v);return $r;}$isUpdate=$id!==null;$data=['name'=>$name,'description'=>$this->postString('description')?:null,'status'=>$this->postString('status')?:'active'];try{if($isUpdate){if(!$m->find($id))throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();$m->update($id,$data);}else{$m->insert($data);$id=(int)$m->getInsertID();}(new AuditService())->log($this->userId(),$isUpdate?'location_updated':'location_created','equipment_location',$id,($isUpdate?'Updated ':'Created ').'equipment location '.$name);return redirect()->back()->with('success',$isUpdate?'Location updated.':'Location created.');}catch(\CodeIgniter\Exceptions\PageNotFoundException $e){throw $e;}catch(\Throwable $e){$r=redirect()->back()->withInput()->with('error',$this->safeErrorMessage($e,'Location could not be saved.'));foreach($context as $k=>$v)$r=$r->with($k,$v);return $r;}}
}
