<?php
namespace App\Controllers;
class EquipmentController extends BaseController {
 public function index(){$filters=['q'=>(string)$this->request->getGet('q'),'status'=>$this->role()==='borrower'?'available':(string)$this->request->getGet('status'),'category_id'=>(int)$this->request->getGet('category_id')];return view('equipment/index',['title'=>$this->role()==='borrower'?'Browse Equipment':'Equipment','equipment'=>$this->repository()->equipment($filters),'categories'=>$this->repository()->categories(true)]);}
 public function show(int $id){$equipment=$this->repository()->findEquipment($id);if(!$equipment||($this->role()==='borrower'&&$equipment['status']!=='available'))throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();return view('equipment/show',['title'=>$equipment['name'],'equipment'=>$equipment]);}
 public function create(){return view('equipment/form',['title'=>'Add Equipment','equipment'=>null,'categories'=>$this->repository()->categories(true),'locations'=>$this->repository()->locations(true)]);}
 public function store(){if(!$this->validate($this->rules()))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());try{$this->equipmentService()->create($this->payload(),$this->userId());return redirect()->to('/equipment')->with('success','Equipment created successfully.');}catch(\Throwable $e){return redirect()->back()->withInput()->with('error',$this->safeErrorMessage($e,'Equipment could not be created.'));}}
 public function edit(int $id){$equipment=$this->repository()->findEquipment($id);if(!$equipment)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();return view('equipment/form',['title'=>'Edit Equipment','equipment'=>$equipment,'categories'=>$this->repository()->categories(),'locations'=>$this->repository()->locations()]);}
 public function update(int $id){if(!$this->validate($this->rules()))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());try{$this->equipmentService()->update($id,$this->payload(),$this->userId());return redirect()->to('/equipment/'.$id)->with('success','Equipment updated successfully.');}catch(\Throwable $e){return redirect()->back()->withInput()->with('error',$this->safeErrorMessage($e,'Equipment could not be updated.'));}}
 private function rules():array{return ['asset_code'=>'required|max_length[40]','name'=>'required|max_length[150]','category_id'=>'required|is_natural_no_zero','location_id'=>'required|is_natural_no_zero','total_quantity'=>'required|is_natural','unit'=>'required|max_length[40]','condition'=>'required|in_list[excellent,good,fair,damaged]','status'=>'required|in_list[available,unavailable,maintenance,retired]','acquired_date'=>'permit_empty|valid_date[Y-m-d]'];}
 private function payload():array{return ['asset_code'=>strtoupper($this->postString('asset_code')),'category_id'=>$this->postPositiveInt('category_id'),'location_id'=>$this->postPositiveInt('location_id'),'name'=>$this->postString('name'),'description'=>$this->postString('description')?:null,'total_quantity'=>(int)$this->postString('total_quantity'),'unit'=>$this->postString('unit'),'condition'=>$this->postString('condition'),'status'=>$this->postString('status'),'acquired_date'=>$this->postString('acquired_date')?:null,'notes'=>$this->postString('notes')?:null];}
}
