<?php
namespace App\Controllers;
class EquipmentController extends BaseController {
 public function index(){$filters=['q'=>(string)$this->request->getGet('q'),'status'=>$this->role()==='borrower'?'available':(string)$this->request->getGet('status'),'category_id'=>(int)$this->request->getGet('category_id')];$page=$this->repository()->equipmentPage($filters,$this->page(),20);return view('equipment/index',['title'=>$this->role()==='borrower'?'Browse Equipment':'Equipment','equipment'=>$page['rows'],'categories'=>$this->repository()->categories(true),'pagerLinks'=>$this->pagerLinks($page['page'],20,$page['total']),'total'=>$page['total']]);}
 public function show(int $id){$equipment=$this->repository()->findEquipment($id);if(!$equipment||($this->role()==='borrower'&&$equipment['status']!=='available'))throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();return view('equipment/show',['title'=>$equipment['name'],'equipment'=>$equipment]);}
 public function create(){return view('equipment/form',['title'=>'Add Equipment','equipment'=>null,'categories'=>$this->repository()->categories(true),'locations'=>$this->repository()->locations(true)]);}
 public function store(){if(!$this->validate('equipment'))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());try{$this->equipmentService()->create($this->payload(),$this->userId());return redirect()->to('/equipment')->with('success','Equipment created successfully.');}catch(\Throwable $e){$message=$this->safeErrorMessage($e,'Equipment could not be created.');if($message==='Asset code is already in use.')return redirect()->back()->withInput()->with('errors',['asset_code'=>$message]);return redirect()->back()->withInput()->with('error',$message);}}
 public function edit(int $id){$equipment=$this->repository()->findEquipment($id);if(!$equipment)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();if($equipment['status']==='retired')return redirect()->to('/equipment/'.$id)->with('error','Restore retired equipment before editing it.');return view('equipment/form',['title'=>'Edit Equipment','equipment'=>$equipment,'categories'=>$this->repository()->categories(true),'locations'=>$this->repository()->locations(true)]);}
 public function update(int $id){if(!$this->validate('equipment'))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());try{$this->equipmentService()->update($id,$this->payload(),$this->userId());return redirect()->to('/equipment/'.$id)->with('success','Equipment updated successfully.');}catch(\Throwable $e){$message=$this->safeErrorMessage($e,'Equipment could not be updated.');if($message==='Asset code is already in use.')return redirect()->back()->withInput()->with('errors',['asset_code'=>$message]);return redirect()->back()->withInput()->with('error',$message);}}
 public function retire(int $id){try{$this->equipmentService()->retire($id,$this->userId());return redirect()->to('/equipment/'.$id)->with('success','Equipment retired.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'Equipment could not be retired.'));}}
 public function restore(int $id){try{$this->equipmentService()->restore($id,$this->userId());return redirect()->to('/equipment/'.$id)->with('success','Equipment restored as unavailable. Review the record before making it available.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'Equipment could not be restored.'));}}
 private function payload():array{return ['asset_code'=>strtoupper($this->postString('asset_code')),'category_id'=>$this->postPositiveInt('category_id'),'location_id'=>$this->postPositiveInt('location_id'),'name'=>$this->postString('name'),'description'=>$this->postString('description')?:null,'total_quantity'=>(int)$this->postString('total_quantity'),'unit'=>$this->postString('unit'),'condition'=>$this->postString('condition'),'status'=>$this->postString('status'),'acquired_date'=>$this->postString('acquired_date')?:null,'notes'=>$this->postString('notes')?:null];}
}
