<?php
namespace App\Controllers;
use App\Application\Services\AuditService;use App\Models\UserModel;
class UsersController extends BaseController {
 public function index(){return view('users/index',['title'=>'Users','users'=>(new UserModel())->orderBy('display_name')->findAll()]);}
 public function store(){if(!$this->validate(['username'=>'required|min_length[3]|max_length[80]','display_name'=>'required|max_length[120]','email'=>'permit_empty|valid_email|max_length[190]','contact_number'=>'permit_empty|max_length[40]','address'=>'permit_empty|max_length[5000]','password'=>'required|min_length[8]|max_length[255]','role'=>'required|in_list[admin,barangay_official,borrower]','status'=>'required|in_list[active,inactive]']))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());$m=new UserModel();if($m->where('username',$this->postString('username'))->first())return redirect()->back()->withInput()->with('error','Username is already in use.');$email=$this->postString('email');if($email&&$m->where('email',$email)->first())return redirect()->back()->withInput()->with('error','Email is already in use.');try{$m->insert(['username'=>$this->postString('username'),'password_hash'=>password_hash($this->postString('password'),PASSWORD_DEFAULT),'display_name'=>$this->postString('display_name'),'email'=>$email?:null,'contact_number'=>$this->postString('contact_number')?:null,'address'=>$this->postString('address')?:null,'role'=>$this->postString('role'),'status'=>$this->postString('status')]);$id=(int)$m->getInsertID();(new AuditService())->log($this->userId(),'user_created','user',$id,'Created user '.$this->postString('username'));return redirect()->back()->with('success','User account created.');}catch(\Throwable $e){return redirect()->back()->withInput()->with('error',$this->safeErrorMessage($e,'User account could not be created.'));}}
 public function update(int $id){$m=new UserModel();$u=$m->find($id);if(!$u)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();if(!$this->validate(['display_name'=>'required|max_length[120]','email'=>'permit_empty|valid_email|max_length[190]','contact_number'=>'permit_empty|max_length[40]','address'=>'permit_empty|max_length[5000]','role'=>'required|in_list[admin,barangay_official,borrower]','status'=>'required|in_list[active,inactive]','password'=>'permit_empty|min_length[8]|max_length[255]']))return redirect()->back()->withInput()->with('errors',$this->validator->getErrors());$email=$this->postString('email');if($email&&$m->where('email',$email)->where('id !=',$id)->first())return redirect()->back()->withInput()->with('error','Email is already in use.');$data=['display_name'=>$this->postString('display_name'),'email'=>$email?:null,'contact_number'=>$this->postString('contact_number')?:null,'address'=>$this->postString('address')?:null,'role'=>$this->postString('role'),'status'=>$this->postString('status')];if($this->postString('password'))$data['password_hash']=password_hash($this->postString('password'),PASSWORD_DEFAULT);if($id===$this->userId()&&($data['status']!=='active'||$data['role']!=='admin'))return redirect()->back()->with('error','You cannot deactivate or remove administrator access from your own account.');if($u['role']==='admin'&&($data['role']!=='admin'||$data['status']!=='active')&&$this->activeAdminCount()<=1)return redirect()->back()->with('error','At least one active administrator account is required.');try{$m->update($id,$data);(new AuditService())->log($this->userId(),'user_updated','user',$id,'Updated user '.$u['username']);return redirect()->back()->with('success','User account updated.');}catch(\Throwable $e){return redirect()->back()->withInput()->with('error',$this->safeErrorMessage($e,'User account could not be updated.'));}}
 public function status(int $id){$m=new UserModel();$u=$m->find($id);if(!$u)throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();$status=$this->postString('status');if(!in_array($status,['active','inactive'],true))return redirect()->back()->with('error','Invalid status.');if($id===$this->userId()&&$status==='inactive')return redirect()->back()->with('error','You cannot deactivate your own account.');if($u['role']==='admin'&&$status==='inactive'&&$this->activeAdminCount()<=1)return redirect()->back()->with('error','At least one active administrator account is required.');try{$m->update($id,['status'=>$status]);(new AuditService())->log($this->userId(),'user_'.$status,'user',$id,ucfirst($status).' user '.$u['username']);return redirect()->back()->with('success','User status updated.');}catch(\Throwable $e){return redirect()->back()->with('error',$this->safeErrorMessage($e,'User status could not be updated.'));}}
 private function activeAdminCount():int{return (new UserModel())->where(['role'=>'admin','status'=>'active'])->countAllResults();}
}
